from app.models.prediction import Prediction
from app.extensions import db


class CropRepository:
    """
    Crop Repository
    Logs predictions generated by the Crop Recommendation engine.
    """

    @staticmethod
    def save_prediction(prediction: Prediction) -> Prediction:
        db.session.add(prediction)
        db.session.commit()
        return prediction

    @staticmethod
    def rollback():
        db.session.rollback()
