"""Add language_preference, country, taluk

Revision ID: 9b3bb6ede6a8
Revises: 48ee2e072da1
Create Date: 2026-06-28 16:30:00.303229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3bb6ede6a8'
down_revision = '48ee2e072da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('taluk', sa.String(length=100), nullable=True))
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_preference', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language_preference')

    with op.batch_alter_table('farms', schema=None) as batch_op:
        batch_op.alter_column('district',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('taluk')
        batch_op.drop_column('country')

    # ### end Alembic commands ###
